### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by JesseWynants** [times/angular-tabletop#2]
Thanks for angular-tabletop, exactly what I was looking for.
Would be great if you could include a simple example.html in the codebase.

**Comment by aendra-rininsland** [comment]
Happy to do so, but think it will really be any more explanatory than the example given in the README?

**Comment by JesseWynants** [comment]
Probably it's just me and my basic angular knowledge. Just trying to get the google sheets data in an angular array and struggling to do so.

**Comment by aendra-rininsland** [comment]
I'll add this to the docs eventually, but here's a working example:

http://plnkr.co/edit/k3qdY0YZ6WofyihT623g

**Comment by JesseWynants** [comment]
This is great! Thanks a lot.

Jesse
